class EventLoop:
    name: str
    def __init__(self) -> None: ...
    def call_soon(self, callback, *args, context=None) -> None: ...
    def run_forever(self) -> None: ...
    def run_until_complete(self, future) -> None: ...
    def get_debug(self) -> bool: ...
    def set_debug(self, enabled: bool) -> None: ...
    def stop(self) -> None: ...
    async def getaddrinfo(self, host, port, *, family=0, type=0, proto=0, flags=0): ...
    async def getnameinfo(self, sockaddr, flags=0): ...
    #
    async def create_connection(
        self,
        protocol_factory,
        host=None,
        port=None,
        *,
        ssl=None,
        family=0,
        proto=0,
        flags=0,
        sock=None,
        local_addr=None,
        server_hostname=None,
        ssl_handshake_timeout=None,
        ssl_shutdown_timeout=None,
        happy_eyeballs_delay=None,
        interleave=None,
    ): ...
