name: Tests

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache Meson packagecache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: subprojects/packagecache
          key: meson-packagecache-${{ runner.os }}-${{ hashFiles('subprojects/*.wrap') }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
        with:
          disable_annotations: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - run: rm C:/Strawberry/perl/bin/ -rf
        shell: bash
        if: runner.os == 'Windows'

      - uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
        if: runner.os == 'Windows'

      - run: pip install -r requirements.txt

      - name: Setup
        run: meson setup build --backend ninja
        env:
          SCCACHE_GHA_ENABLED: "true"

      - name: Build
        run: ninja -C build copy

      - run: python e2e.py
        timeout-minutes: 10
        env:
          PYTHONPATH: "src"
